- name: Install prerequisites for Docker repository
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    - jq
    - python3-passlib
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: Add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker apt repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
  
- name: Install docker and it's dependencies
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
  notify: restart_docker
