- name: Install prerequisites for Docker repository
  dnf:
    name:
    - ca-certificates
    - curl
    - gnupg2
    - jq
    - python3-passlib
    - python3
    state: latest

- name: Add docker repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    file: docker-ce-stable
    baseurl: https://download.docker.com/linux/centos/8/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes
    
- name: Install docker and it's dependencies
  dnf:
    name:        
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes
  notify: restart_docker

- name: Checking firewalld status
  command: systemctl status firewalld
  ignore_errors: yes
  register: firewalld_state

- name: Open monitoring server ports with firewalld
  firewalld:
    immediate: yes
    permanent: yes
    port: "{{ item }}"
    state: enabled
    zone: public
  loop:
    - "3000/tcp"
    - "8086/tcp"
    - "8888/tcp"
  when: "'active (running)' in firewalld_state.stdout"