- name: Install epel-release package in centos
  dnf: 
    name: 
      - epel-release
    state: latest
  when: ansible_facts['distribution'] == "CentOS"

- name: Install epel-release package in oracle
  dnf: 
    name: 
      - oracle-epel-release-el8
    state: latest
  when: ansible_facts['distribution'] == "OracleLinux"

- name: Install system packages
  dnf:
    name:
      - vim
      - mc
      - htop
      - rsyslog
      - wget
      - gnupg
      - ca-certificates
      - curl
      - bind-utils
      - jq
      - bash-completion
      - python3-libselinux
    state: latest

- block:
    - name: Install chrony package
      dnf:
        name: chrony
        state: latest

    - name: Copy the chrony.conf file
      template:
        src: chrony.conf.j2
        dest: /etc/chrony.conf
      notify: "restart chronyd"
  when: ntp_enabled is defined and ntp_enabled|bool

- name: Disable SELinux at next reboot
  selinux:
    state: disabled

- name: Set SELinux in permissive mode until the machine is rebooted
  command: setenforce 0
  ignore_errors: true
  changed_when: false