---

- name: Restart ntp service
  systemd:
    name: ntp
    enabled: true
    state: restarted
  listen: "restart ntp"

- name: Restart chronyd service
  systemd:
    name: chronyd
    enabled: true
    state: restarted
  listen: "restart chronyd"

- name: Start disable-transparent-huge-pages service
  systemd:
    daemon_reload: true
    name: disable-transparent-huge-pages
    state: restarted
    enabled: true
  listen: "restart disable-thp"